version: '3'
services:
  web:
    container_name: todo_app
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./usr/src/app:/usr/src/app
    tty: true
    stdin_open: true
    ports:
      - '3010:3010'
    # command: npm run watch
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
